# version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"        # Cổng chính để truy cập từ host
      - "443:443"      # Nếu bạn muốn sử dụng HTTPS
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # Thư mục chứa cấu hình Nginx
      - ./nginx/certs:/etc/nginx/certs    # Thư mục chứa chứng chỉ SSL (nếu sử dụng HTTPS)
    depends_on:
      - frontend
      - app
      - image-service
      - fluentd
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.nginx_proxy

  app:
    container_name: application
    build:
      context: ./backend
    expose:                           # Sử dụng `expose` thay vì `ports`
      - "81"
    volumes:
      - ./backend/uploads:/app/uploads  # Mount thư mục uploads của backend
    depends_on:
      - db
      - elasticsearch
      - image-service
      - fluentd
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - BASE_SEARCH_API_URL=${BASE_SEARCH_API_URL}
      - BASE_API_URL=${BASE_API_URL}
      - BASE_FE_URL=${BASE_FE_URL}
      - BASE_BE_URL=${BASE_BE_URL}
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.application

  image-service:
    container_name: image_service
    build:
      context: ./image-service
    expose:
      - "82"
    volumes:
      - ./image-service/images:/app/images/uploads  # Mount thư mục uploads của image-service
    depends_on:
      - db
      - fluentd
    environment:
      - BASE_BE_URL=${BASE_BE_URL}
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.image_service

  search-service:
    container_name: search_service
    build:
      context: ./search-service
    expose:
      - "82"
    # volumes:
    #   - ./search-service/images:/app/images/uploads  # Mount thư mục uploads của image-service
    depends_on:
      - db
      - fluentd
      # - elasticsearch
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - BASE_BE_URL=${BASE_BE_URL}
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.search_service

  db:
    image: postgres:13
    container_name: database
    restart: always
    depends_on:
      - fluentd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432" # Cổng này chỉ để truy cập từ host, không cần thiết cho kết nối giữa các container
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.database

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    depends_on:
      - fluentd
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - fluentd
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.kibana
  # Thêm Fluentd
  fluentd:
    image: fluent/fluentd:v1.14-debian-1
    container_name: fluentd
    ports:
      - "24224:24224"       # Port mặc định cho Fluentd
      - "24224:24224/udp"   # Port UDP cho Fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc    # Thư mục cấu hình Fluentd
      - ./logs:/fluentd/log            # Thư mục lưu trữ log
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:24224"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"  # Bạn có thể giữ hoặc loại bỏ dòng này nếu muốn frontend chỉ truy cập thông qua Nginx
    depends_on:
      - fluentd
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.frontend

  # Thêm Prometheus
  prometheus:
    image: prom/prometheus:latest
    depends_on:
      - fluentd
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # Loại bỏ ports để Prometheus chỉ truy cập thông qua Nginx
    # ports:
    #   - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/prometheus'
      - '--web.external-url=https://insight.io.vn/prometheus/'
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.prometheus

  # Thêm Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # Loại bỏ ports để Grafana chỉ truy cập thông qua Nginx
    # ports:
    #   - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Đặt mật khẩu admin cho Grafana
      - GF_SERVER_ROOT_URL=https://insight.io.vn/grafana/
    depends_on:
      - prometheus
      - fluentd
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.grafana

  # Sửa đổi Exporter cho PostgreSQL
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres_exporter
    environment:
      - DATA_SOURCE_NAME=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    expose:
      - "9187"
    ports:
      - "9187:9187"  # Bạn có thể loại bỏ dòng này nếu không muốn expose trực tiếp
    depends_on:
      - db
      - fluentd
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.postgres_exporter

  # Thêm Elasticsearch Exporter
  elasticsearch-exporter:
    image: justwatch/elasticsearch_exporter:latest
    container_name: elasticsearch_exporter
    environment:
      - DATA_SOURCE_NAME=http://elasticsearch:9200
    expose:
      - "9114"
    ports:
      - "9114:9114"  # Bạn có thể loại bỏ dòng này nếu không muốn expose trực tiếp
    depends_on:
      - elasticsearch
      - fluentd
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.elasticsearch_exporter

  # Thêm Node Exporter để giám sát tài nguyên hệ thống (Tùy chọn nhưng hữu ích)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    depends_on:
      - fluentd
    ports:
      - "9100:9100"  # Bạn có thể loại bỏ dòng này nếu không muốn expose trực tiếp
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.node_exporter

  # Thêm Nginx Prometheus Exporter
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    environment:
      - NGINX_STATUS_URL=http://nginx_proxy/nginx_status  # URL để lấy trạng thái Nginx
    expose:
      - "9113"
    ports:
      - "9113:9113"  # Bạn có thể loại bỏ dòng này nếu không muốn expose trực tiếp
    depends_on:
      - nginx
      - fluentd
    networks:
      - app-network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: docker.nginx_exporter

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  es-data:
  grafana-data:







# version: '3.7'

# services:
#   app:
#     container_name: application
#     build:
#       context: ./backend
#     ports:
#       - "81:81"
#     volumes:
#       - ./backend/uploads:/app/uploads  # Mount thư mục uploads của backend
#     depends_on:
#       - db
#       - elasticsearch
#       - image-service
#     environment:
#       - DB_HOST=db
#       - DB_PORT=5432
#       - DB_USER=postgres
#       - DB_PASSWORD=postgres
#       - DB_NAME=postgres
#       - ELASTICSEARCH_HOST=http://elasticsearch:9200
#       - JWT_SECRET=${JWT_SECRET}
#       - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#       - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#       - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
#       - BASE_API_URL=${BASE_API_URL}
#       - BASE_FE_URL=${BASE_FE_URL}
#       - BASE_BE_URL=${BASE_BE_URL}

#     networks:
#       - app-network

#   image-service:
#     container_name: image_service
#     build:
#       context: ./image-service
#     ports:
#       - "82:82"
#     volumes:
#       - ./image-service/uploads:/app/images/uploads  # Mount thư mục uploads của image-service
#     depends_on:
#       - db
#       - elasticsearch
#     networks:
#       - app-network

#   db:
#     image: postgres:13
#     container_name: database
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: postgres
#     ports:
#       - "5433:5432" # Cổng này chỉ để truy cập từ host, không cần thiết cho kết nối giữa các container
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     networks:
#       - app-network

#   elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
#     container_name: elasticsearch
#     environment:
#       - discovery.type=single-node
#       - ES_JAVA_OPTS=-Xms512m -Xmx512m
#     ports:
#       - "9200:9200"
#     volumes:
#       - es-data:/usr/share/elasticsearch/data
#     networks:
#       - app-network

#   kibana:
#     image: docker.elastic.co/kibana/kibana:7.17.10
#     container_name: kibana
#     environment:
#       - ELASTICSEARCH_HOST=http://elasticsearch:9200
#     ports:
#       - "5601:5601"
#     depends_on:
#       - elasticsearch
#     networks:
#       - app-network

#   frontend:
#     container_name: frontend
#     build:
#       context: ./frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - elasticsearch
#       - image-service
#     networks:
#       - app-network

#   # Thêm Prometheus
#   prometheus:
#     image: prom/prometheus:latest
#     container_name: prometheus
#     volumes:
#       - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"
#     networks:
#       - app-network

#   # Thêm Grafana
#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     ports:
#       - "3001:3000"  # Port 3001 trên host sẽ ánh xạ tới port 3000 của Grafana
#     volumes:
#       - grafana-data:/var/lib/grafana
#     environment:
#       - GF_SECURITY_ADMIN_PASSWORD=admin  # Đặt mật khẩu admin cho Grafana
#     depends_on:
#       - prometheus
#     networks:
#       - app-network

#   # Sửa đổi Exporter cho PostgreSQL
#   postgres-exporter:
#     image: prometheuscommunity/postgres-exporter:latest
#     container_name: postgres_exporter
#     environment:
#       - DATA_SOURCE_NAME=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
#     ports:
#       - "9187:9187"
#     depends_on:
#       - db
#     networks:
#       - app-network

#   # Thêm Elasticsearch Exporter
#   elasticsearch-exporter:
#     image: justwatch/elasticsearch_exporter:latest
#     container_name: elasticsearch_exporter
#     ports:
#       - "9114:9114"
#     environment:
#       - DATA_SOURCE_NAME=http://elasticsearch:9200
#     depends_on:
#       - elasticsearch
#     networks:
#       - app-network

#   # Thêm Node Exporter để giám sát tài nguyên hệ thống (Tùy chọn nhưng hữu ích)
#   node-exporter:
#     image: prom/node-exporter:latest
#     container_name: node_exporter
#     ports:
#       - "9100:9100"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   db-data:
#   es-data:
#   grafana-data:

