name: CI/CD Deployment

on:
  push:
    branches:
      - main  # Hoặc nhánh bạn muốn theo dõi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Kiểm tra mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Thiết lập SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Bước 3: Copy mã nguồn lên server
      - name: Copy project files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          source: "."  # Sao chép toàn bộ repository, bạn có thể điều chỉnh nếu cần
          target: ${{ secrets.DEPLOY_PATH }}

      # Bước 4: Kết nối SSH và chạy Docker Compose
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            docker-compose pull  # Kéo các image mới nếu sử dụng image từ registry
            docker-compose up -d --build
            docker system prune -f  # Dọn dẹp các container, image không sử dụng
